// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDleE5FQ4wenmroX9WQ3p6Z9YeV1u0GC_w',
    appId: '1:315126696861:web:21a8a71b523bd623493d74',
    messagingSenderId: '315126696861',
    projectId: 'flutter-todo-a7b2b',
    authDomain: 'flutter-todo-a7b2b.firebaseapp.com',
    storageBucket: 'flutter-todo-a7b2b.firebasestorage.app',
    measurementId: 'G-9CM85RTJJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs7oBvS9aSY7yayo4hQbXKCYezMneSioE',
    appId: '1:315126696861:android:72c37effa47890fe493d74',
    messagingSenderId: '315126696861',
    projectId: 'flutter-todo-a7b2b',
    storageBucket: 'flutter-todo-a7b2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANY0jAYWUr7CvnMQM1HVBPF8rOqTcVX8U',
    appId: '1:315126696861:ios:dc93d7a550c31316493d74',
    messagingSenderId: '315126696861',
    projectId: 'flutter-todo-a7b2b',
    storageBucket: 'flutter-todo-a7b2b.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANY0jAYWUr7CvnMQM1HVBPF8rOqTcVX8U',
    appId: '1:315126696861:ios:dc93d7a550c31316493d74',
    messagingSenderId: '315126696861',
    projectId: 'flutter-todo-a7b2b',
    storageBucket: 'flutter-todo-a7b2b.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDleE5FQ4wenmroX9WQ3p6Z9YeV1u0GC_w',
    appId: '1:315126696861:web:bf2ddfc1270b44a3493d74',
    messagingSenderId: '315126696861',
    projectId: 'flutter-todo-a7b2b',
    authDomain: 'flutter-todo-a7b2b.firebaseapp.com',
    storageBucket: 'flutter-todo-a7b2b.firebasestorage.app',
    measurementId: 'G-51P7XS0198',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDleE5FQ4wenmroX9WQ3p6Z9YeV1u0GC_w',
    appId: '1:315126696861:web:21a8a71b523bd623493d74',
    messagingSenderId: '315126696861',
    projectId: 'flutter-todo-a7b2b',
    authDomain: 'flutter-todo-a7b2b.firebaseapp.com',
    storageBucket: 'flutter-todo-a7b2b.firebasestorage.app',
    measurementId: 'G-9CM85RTJJ0',
  );
}
